<?xml version="1.0" encoding="utf-8"?>
<!-- ECUFlash STANDARD UNITS ECU DEFINITION FILE (VERSION E2UE102B_v1) 2010-10-03

TERMS, CONDITIONS, AND DISCLAIMERS
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
WARNING: These definition files are created as the result of the extremely complex and time consuming
process of reverse-engineering the factory ECU. Because of this complexity, it is necessary to make certain
assumptions and, therefore, it is impossible to always deal in absolutes in regards to representations made
by these definitions. In addition, due to this complexity and the numerous variations among different ECUs,
it is also impossible to guarantee that the definitions will not contain errors or other bugs. What this all means
is that there is the potential for bugs, errors and misrepresentations which can result in damage to your motor,
your ECU as well the possibility of causing your vehicle to behave unexpectedly on the road, increasing the
risk of death or injury. Modifications to your vehicle's ECU may also be in violation of local, state and federal
laws. By using these definition files, either directly or indirectly, you agree to assume 100% of all risk and
RomRaider's creators and contributors shall not be held responsible for any damages or injuries you receive.
This product is for advanced users only. There are no safeguards in place when tuning with RomRaider. As such,
the potential for serious damage and injury still exists, even if the user does not experience any bugs or errors. 

As always, use at your own risk.

These definitions are created for FREE without any sort of guarantee. The developers cannot be held liable
for any damage or injury incurred as a result of these definitions. USE AT YOUR OWN RISK!-->
<!DOCTYPE rom[

<!ELEMENT rom ( scales?, tables? ) >
<!ATTLIST rom name ID #REQUIRED >
<!ATTLIST rom abstract CDATA "false" >
<!ATTLIST rom idaddress CDATA #IMPLIED >
<!ATTLIST rom idstring CDATA #IMPLIED >
<!ATTLIST rom base CDATA #IMPLIED >
<!ATTLIST rom description CDATA #IMPLIED >
<!ATTLIST rom memmodel IDREF #IMPLIED >
<!ATTLIST rom flashmethod IDREF #IMPLIED >
<!ATTLIST rom caseid IDREF #IMPLIED >
<!ATTLIST rom obsolete CDATA "false" >

<!ELEMENT tables ( category+ ) >

<!ELEMENT table3d ( xaxis?, yaxis?, description? ) >
<!ATTLIST table3d name ID #REQUIRED >
<!ATTLIST table3d userlevel (0|1|2|3|4|5) "0" >
<!ATTLIST table3d scale IDREF #IMPLIED >
<!ATTLIST table3d address CDATA #IMPLIED >
<!ATTLIST table3d xaddress CDATA #IMPLIED >
<!ATTLIST table3d yaddress CDATA #IMPLIED >
<!ATTLIST table3d sizex CDATA #IMPLIED >
<!ATTLIST table3d sizey CDATA #IMPLIED >

<!ELEMENT table2d ( axis?, description? ) >
<!ATTLIST table2d name ID #REQUIRED >
<!ATTLIST table2d userlevel (0|1|2|3|4|5) "0" >
<!ATTLIST table2d scale IDREF #IMPLIED >
<!ATTLIST table2d address CDATA #IMPLIED >
<!ATTLIST table2d size CDATA #IMPLIED >
<!ATTLIST table2d axisaddress CDATA #IMPLIED >

<!ELEMENT parameter ( description? ) >
<!ATTLIST parameter name ID #REQUIRED >
<!ATTLIST parameter userlevel (0|1|2|3|4|5) "0" >
<!ATTLIST parameter scale IDREF #IMPLIED >
<!ATTLIST parameter address CDATA #IMPLIED >

<!ELEMENT switch ( description?, on?, off? ) >
<!ATTLIST switch name ID #REQUIRED >
<!ATTLIST switch userlevel (0|1|2|3|4|5) "0" >
<!ATTLIST switch address CDATA #IMPLIED >
<!ATTLIST switch size CDATA "1" >
<!ATTLIST switch hidden (true|false) "false" >
<!ATTLIST switch default (on|off|none) "none" >

<!ELEMENT switchgroup ( switch* ) >
<!ATTLIST switchgroup name ID #REQUIRED >
<!ATTLIST switchgroup default (on|off|none) "none" >
<!ATTLIST switchgroup userlevel (0|1|2|3|4|5) "0" >
<!ATTLIST switchgroup hidden (true|false) "false" >
<!ATTLIST switchgroup description CDATA #IMPLIED >

<!ELEMENT description ( #PCDATA ) >

<!ELEMENT axis ( data? ) >
<!ATTLIST axis name ID #REQUIRED >
<!ATTLIST axis scale IDREF #IMPLIED >
<!ATTLIST axis address CDATA #IMPLIED >
<!ATTLIST axis size CDATA "1" >
<!ATTLIST axis static (true|false) "false" >

<!ELEMENT xaxis ( data? ) >
<!ATTLIST xaxis name ID #REQUIRED >
<!ATTLIST xaxis scale IDREF #IMPLIED >
<!ATTLIST xaxis address CDATA #IMPLIED >
<!ATTLIST xaxis size CDATA "1" >

<!ELEMENT yaxis ( data? ) >
<!ATTLIST yaxis name ID #REQUIRED >
<!ATTLIST yaxis scale IDREF #IMPLIED >
<!ATTLIST yaxis address CDATA #IMPLIED >
<!ATTLIST yaxis size CDATA "1" >

<!ELEMENT data ( #PCDATA ) >

<!ELEMENT on EMPTY >
<!ATTLIST on name ID #REQUIRED >
<!ATTLIST on data CDATA #REQUIRED >

<!ELEMENT off EMPTY >
<!ATTLIST off name ID #REQUIRED >
<!ATTLIST off data CDATA #REQUIRED >

<!ELEMENT category ( table3d*, table2d*, parameter*, switch*, string* ) >
<!ATTLIST category name ID #REQUIRED >
<!ATTLIST category description CDATA #IMPLIED >

<!ELEMENT scales ( scale+ ) >

<!ELEMENT scale ( unit+ ) >
<!ATTLIST scale name ID #REQUIRED >
<!ATTLIST scale storagetype (uint8|int8|uint16|int16|float|hex|char) "uint8" >
<!ATTLIST scale endian (big|little) "big" >
<!ATTLIST scale logparam IDREF #IMPLIED >

<!ELEMENT unit EMPTY >
<!ATTLIST unit name ID #REQUIRED >
<!ATTLIST unit system (stantard|metric|universal) "universal" >
<!ATTLIST unit to_real CDATA #REQUIRED >
<!ATTLIST unit to_byte CDATA #REQUIRED >
<!ATTLIST unit format CDATA "0.00" >
<!ATTLIST unit coarseincrement CDATA "1" >
<!ATTLIST unit fineincrement CDATA "0.1" >
]>
<rom abstract="false" obsolete="false">
    <romid>
        <xmlid>E2UE102B</xmlid>
        <internalidaddress>2000</internalidaddress>
        <internalidstring>E2UE102B</internalidstring>
        <ecuid>4B12187007</ecuid>
        <year>07</year>
        <market>USDM</market>
        <make>Subaru</make>
        <model>Outback</model>
        <submodel>2.5i</submodel>
        <transmission>MT</transmission>
        <memmodel>SH7058</memmodel>
        <flashmethod>subarucan</flashmethod>
        <checksummodule>subarudbw</checksummodule>
    </romid>
    <include>32BITBASE</include>
    <table1d name="Manifold Pressure Sensor Scaling" address="c0288" />
    <table1d name="Manifold Pressure Sensor Limits (CEL)" address="d0578" />
    <table1d name="Manifold Pressure Sensor CEL Delays" address="c482a" />
    <table3d name="Primary Open Loop Fueling A_" address="ca904" userlevel="0">
        <xaxis address="ca888" size="1" />
        <yaxis address="ca8b4" size="1" />
    </table3d>
    <table3d name="Primary Open Loop Fueling B_" address="caa5c" userlevel="0">
        <xaxis address="ca9e0" size="1" />
        <yaxis address="caa0c" size="1" />
    </table3d>
    <table2d name="Front Oxygen Sensor Scaling" address="d0b74" userlevel="0">
        <yaxis address="d0b40" size="1" />
    </table2d>
    <table1d name="Front Oxygen Sensor Rich Limit" address="24994" />
    <table2d name="Front Oxygen Sensor Compensation (Atm. Pressure)" address="c28a8" userlevel="0">
        <yaxis address="c2898" size="1" />
    </table2d>
    <table3d name="CL Fueling Target Compensation A (Load)" address="cb194" userlevel="0">
        <xaxis address="cb11c" size="1" />
        <yaxis address="cb148" elements="19" size="1" />
    </table3d>
    <table3d name="CL Fueling Target Compensation B (Load)" address="cb3b0" userlevel="0">
        <xaxis address="cb338" size="1" />
        <yaxis address="cb364" elements="19" size="1" />
    </table3d>
    <table2d name="CL Fueling Target Compensation (ECT)_" address="c9218" userlevel="0">
        <yaxis address="c91d8" size="1" />
    </table2d>
    <table1d name="CL Fueling Target Compensation (ECT) Disable" address="c7738" />
    <table2d name="CL to OL Delay A (Atm. Pressure)" address="c95c4" userlevel="0">
        <yaxis address="c95a8" size="1" />
    </table2d>
    <table2d name="CL to OL Delay B (Atm. Pressure)" address="c95f0" userlevel="0">
        <yaxis address="c95d4" size="1" />
    </table2d>
    <table2d name="CL to OL Transition with Delay (Accelerator)" address="c8298" userlevel="0">
        <yaxis address="c8258" size="1" />
    </table2d>
    <table1d name="CL to OL Transition with Delay Throttle Hysteresis" address="c7908" />
    <table2d name="CL to OL Transition with Delay (Base Pulse Width)" address="c9640" userlevel="0">
        <yaxis address="c9600" size="1" />
    </table2d>
    <table1d name="CL to OL Transition with Delay BPW Hysteresis" address="c790c" />
    <table1d name="CL Delay Minimum (ECT)" address="c7910" />
    <table1d name="CL Delay Maximum Engine Speed A" address="c7914" />
    <table1d name="CL Delay Maximum Engine Speed B" address="c7920" />
    <table1d name="CL Delay Engine Speed B Counter Threshold" address="c74b6" />
    <table1d name="CL Delay Maximum (Throttle) A" address="c791c" />
    <table1d name="CL Delay Throttle A Counter Threshold" address="c74b4" />
    <table2d name="CL Delay Maximum (Throttle) B (ECT)" address="c82a8" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table3d name="Injector Latency_" address="cacc4" userlevel="0">
        <xaxis address="caca4" size="1" />
        <yaxis address="cacb8" size="1" />
    </table3d>
    <table1d name="Injector Flow Scaling" address="c7620" />
    <table3d name="Per Injector Primary Fuel Offset Compensation A" address="ca280" userlevel="0">
        <xaxis address="ca244" size="1" />
        <yaxis address="ca264" elements="7" size="1" />
    </table3d>
    <table3d name="Per Injector Primary Fuel Offset Compensation B" address="ca2f4" userlevel="0">
        <xaxis address="ca2b8" size="1" />
        <yaxis address="ca2d8" elements="7" size="1" />
    </table3d>
    <table3d name="Per Injector Primary Fuel Offset Compensation C" address="ca368" userlevel="0">
        <xaxis address="ca32c" size="1" />
        <yaxis address="ca34c" elements="7" size="1" />
    </table3d>
    <table3d name="Per Injector Primary Fuel Offset Compensation D" address="ca3dc" userlevel="0">
        <xaxis address="ca3a0" size="1" />
        <yaxis address="ca3c0" elements="7" size="1" />
    </table3d>
    <table2d name="Cranking Fuel Injector Pulse Width A (ECT)" address="c86b6" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width B (ECT)" address="c86d6" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width C (ECT)" address="c86f6" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width D (ECT)" address="c8716" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width E (ECT)" address="c8736" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width F (ECT)" address="c8756" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width G (ECT)" address="c8776" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width H (ECT)" address="c8796" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width I (ECT)" address="c87b6" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width J (ECT)" address="c87d6" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width K (ECT)" address="c87f6" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width L (ECT)" address="c8816" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width M (ECT)" address="c8836" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width N (ECT)" address="c8856" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width O (ECT)" address="c8876" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width P (ECT)" address="c8896" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width Q (ECT)" address="c88b6" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width R (ECT)" address="c88d6" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width S (ECT)" address="c88f6" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width T (ECT)" address="c8916" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Cranking Fuel Injector Pulse Width U (ECT)" address="c8936" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table3d name="Cranking Fuel IPW Compensation A (RPM)" address="ca500" userlevel="0">
        <xaxis address="ca4d0" size="1" />
        <yaxis address="ca4e4" size="1" />
    </table3d>
    <table3d name="Cranking Fuel IPW Compensation B (RPM)" address="ca55c" userlevel="0">
        <xaxis address="ca524" size="1" />
        <yaxis address="ca538" elements="9" size="1" />
    </table3d>
    <table2d name="Cranking Fuel IPW Compensation (MAP)" address="c7efc" userlevel="0">
        <yaxis address="c7ed4" size="1" />
    </table2d>
    <table2d name="Cranking Fuel IPW Compensation (Accelerator)" address="c7f20" userlevel="0">
        <yaxis address="c7f08" size="1" />
    </table2d>
    <table2d name="Throttle Tip-in Enrichment A" address="c9dc0" userlevel="0">
        <yaxis address="c9d78" size="1" />
    </table2d>
    <table2d name="Throttle Tip-in Enrichment B" address="c9e2c" userlevel="0">
        <yaxis address="c9de4" size="1" />
    </table2d>
    <table1d name="Minimum Tip-in Enrichment Activation" address="c7af8" />
    <table1d name="Minimum Tip-in Enrichment Activation (Throttle)" address="c7af4" />
    <table2d name="Tip-in Enrichment Compensation (RPM)" address="c8488" userlevel="0">
        <yaxis address="c8464" size="1" />
    </table2d>
    <table2d name="Tip-in Enrichment Compensation (MRP)" address="c84b8" userlevel="0">
        <yaxis address="c8494" size="1" />
    </table2d>
    <table2d name="Tip-in Enrichment Compensation A (ECT)" address="c84c1" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Tip-in Enrichment Compensation B (ECT)" address="c9e50" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Tip-in Enrichment Compensation C (ECT)" address="c9e70" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Tip-in Enrichment Compensation D (ECT)" address="c9e90" userlevel="0">
        <yaxis address="c7484" size="1" />
    </table2d>
    <table1d name="Tip-in Enrichment Compensation D (ECT) Activation" address="c7afc" />
    <table2d name="Tip-in Enrichment Disable Applied Counter Threshold A (ECT)" address="c84d1" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Tip-in Enrichment Disable Applied Counter Threshold B (ECT)" address="c84e1" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table1d name="Tip-in Enrichment Applied Counter Reset" address="c7458" />
    <table2d name="Tip-in Enrichment Disable Throttle Cumulative Threshold A (ECT)" address="c9eb0" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table2d name="Tip-in Enrichment Disable Throttle Cumulative Threshold B (ECT)" address="c9ed0" userlevel="0">
        <yaxis address="c7c34" size="1" />
    </table2d>
    <table1d name="Tip-in Throttle Cumulative Reset" address="c7459" />
    <table1d name="A/F Learning #1 Limits" address="c77fc" />
    <table1d name="A/F Learning #1 Airflow Ranges" address="c7808" />
    <table2d name="MAF Sensor Scaling" address="d0a80" userlevel="0">
        <yaxis address="d09c0" elements="48" size="1" />
    </table2d>
    <table3d name="MAF Compensation A (IAT)" address="c361c" userlevel="0">
        <xaxis address="c35e8" size="1" />
        <yaxis address="c35fc" size="1" />
    </table3d>
    <table3d name="MAF Compensation B (IAT)" address="c3678" userlevel="0">
        <xaxis address="c3644" size="1" />
        <yaxis address="c3658" size="1" />
    </table3d>
    <table1d name="Engine Load Limit (Maximum)" address="2217c" />
    <table3d name="Engine Load Compensation A (MP)" address="c32c4" userlevel="0">
        <xaxis address="c3268" size="1" />
        <yaxis address="c3294" size="1" />
    </table3d>
    <table3d name="Engine Load Compensation B (MP)" address="c33a4" userlevel="0">
        <xaxis address="c3348" size="1" />
        <yaxis address="c3374" size="1" />
    </table3d>
    <table3d name="Engine Load Compensation A (Throttle)" address="c3484" userlevel="0">
        <xaxis address="c3428" size="1" />
        <yaxis address="c3454" size="1" />
    </table3d>
    <table3d name="Engine Load Compensation B (Throttle)" address="c3564" userlevel="0">
        <xaxis address="c3508" size="1" />
        <yaxis address="c3534" size="1" />
    </table3d>
    <table3d name="Base Timing A" address="cd704" userlevel="0">
        <xaxis address="cc60c" elements="14" size="1" />
        <yaxis address="cc644" elements="19" size="1" />
    </table3d>
    <table3d name="Base Timing B" address="cd80e" userlevel="0">
        <xaxis address="cc60c" elements="14" size="1" />
        <yaxis address="cc644" elements="19" size="1" />
    </table3d>
    <table3d name="Base Timing C" address="cd918" userlevel="0">
        <xaxis address="cc60c" elements="14" size="1" />
        <yaxis address="cc644" elements="19" size="1" />
    </table3d>
    <table3d name="Base Timing D" address="cda22" userlevel="0">
        <xaxis address="cc60c" elements="14" size="1" />
        <yaxis address="cc644" elements="19" size="1" />
    </table3d>
    <table3d name="Base Timing E" address="cdb2c" userlevel="0">
        <xaxis address="cc60c" elements="14" size="1" />
        <yaxis address="cc644" elements="19" size="1" />
    </table3d>
    <table3d name="Base Timing F" address="cdc36" userlevel="0">
        <xaxis address="cc60c" elements="14" size="1" />
        <yaxis address="cc644" elements="19" size="1" />
    </table3d>
    <table2d name="Base Timing Idle A (In-Gear)(Above Speed Threshold)" address="ccbae" userlevel="0">
        <yaxis address="cc5e8" size="1" />
    </table2d>
    <table3d name="Base Timing Idle B (In-Gear)(Above Speed Threshold)_" address="cd6dc" userlevel="0">
        <xaxis address="cd6a4" size="1" />
        <yaxis address="cd6cc" size="1" />
    </table3d>
    <table2d name="Base Timing Idle A (In-Gear)(Below Speed Threshold)" address="ccbd2" userlevel="0">
        <yaxis address="cc5e8" size="1" />
    </table2d>
    <table2d name="Base Timing Idle B (In-Gear)(Below Speed Threshold)" address="ccbe4" userlevel="0">
        <yaxis address="cc5e8" size="1" />
    </table2d>
    <table2d name="Base Timing Idle A (Neutral)_" address="ccc44" userlevel="0">
        <yaxis address="ccc20" size="1" />
    </table2d>
    <table2d name="Base Timing Idle B (Neutral)_" address="ccca4" userlevel="0">
        <yaxis address="ccc80" size="1" />
    </table2d>
    <table1d name="Base Timing Idle Vehicle Speed Threshold" address="cc360" />
    <table3d name="Knock Correction Advance Max A" address="ce1a8" userlevel="0">
        <xaxis address="ce124" elements="14" size="1" />
        <yaxis address="ce15c" elements="19" size="1" />
    </table3d>
    <table3d name="Knock Correction Advance Max B" address="ce338" userlevel="0">
        <xaxis address="ce2b4" elements="14" size="1" />
        <yaxis address="ce2ec" elements="19" size="1" />
    </table3d>
    <table2d name="Timing Compensation (IAT)" address="ccdd0" userlevel="0">
        <yaxis address="ccd90" size="1" />
    </table2d>
    <table1d name="Timing Comp Min Load (IAT)" address="cc3b4" />
    <table2d name="Timing Compensation A (ECT)" address="ccd4d" userlevel="0">
        <yaxis address="cc6b0" size="1" />
    </table2d>
    <table2d name="Timing Compensation B (ECT)" address="ccd5d" userlevel="0">
        <yaxis address="cc6b0" size="1" />
    </table2d>
    <table2d name="Timing Compensation C (ECT)" address="ccd6d" userlevel="0">
        <yaxis address="cc6b0" size="1" />
    </table2d>
    <table2d name="Timing Compensation D (ECT)" address="ccd7d" userlevel="0">
        <yaxis address="cc6b0" size="1" />
    </table2d>
    <table2d name="Timing Compensation Per Cylinder A__" address="cd11c" userlevel="0">
        <yaxis address="cd0e0" elements="15" size="1" />
    </table2d>
    <table2d name="Timing Compensation Per Cylinder B__" address="cd168" userlevel="0">
        <yaxis address="cd12c" elements="15" size="1" />
    </table2d>
    <table2d name="Timing Compensation Per Cylinder C__" address="cd1b4" userlevel="0">
        <yaxis address="cd178" elements="15" size="1" />
    </table2d>
    <table2d name="Timing Compensation Per Cylinder D__" address="cd200" userlevel="0">
        <yaxis address="cd1c4" elements="15" size="1" />
    </table2d>
    <table1d name="Timing Comp Minimum Load (Per Cylinder)" address="cc4f0" />
    <table1d name="Timing Comp Maximum RPM (Per Cylinder)" address="cc4ec" />
    <table1d name="Timing Comp Minimum Coolant Temp (Per Cylinder)" address="cc4f4" />
    <table1d name="Feedback Correction Range (RPM)" address="cc510" />
    <table2d name="Feedback Correction Minimum Load_" address="cd2d4" userlevel="0">
        <yaxis address="cd2c4" size="1" />
    </table2d>
    <table2d name="Feedback Correction Retard Value_" address="cd5a0" userlevel="0">
        <yaxis address="cd56c" size="1" />
    </table2d>
    <table1d name="Feedback Correction Retard Limit" address="cc4fc" />
    <table1d name="Feedback Correction Negative Advance Value" address="cc500" />
    <table2d name="Feedback Correction Negative Advance Delay_" address="cd310" userlevel="0">
        <yaxis address="cd2dc" size="1" />
    </table2d>
    <table1d name="Fine Correction Range (RPM)" address="cc584" />
    <table1d name="Fine Correction Range (Load)" address="cc594" />
    <table1d name="Fine Correction Rows (RPM)_" address="cc5c0" />
    <table1d name="Fine Correction Columns (Load)_" address="cc5a4" />
    <table2d name="Fine Correction Retard Value_" address="cd608" userlevel="0">
        <yaxis address="cd5d4" size="1" />
    </table2d>
    <table1d name="Fine Correction Retard Limit" address="cc57c" />
    <table1d name="Fine Correction Advance Value" address="cc580" />
    <table1d name="Fine Correction Advance Limit" address="cc578" />
    <table1d name="Fine Correction Advance Delay" address="cc1d6" />
    <table1d name="Rough Correction Range (RPM)" address="cc530" />
    <table1d name="Rough Correction Range (Load)" address="cc540" />
    <table1d name="Rough Correction Minimum KC Advance Map Value" address="cc550" />
    <table2d name="Rough Correction Learning Delay (Increasing)" address="cd238" userlevel="0">
        <yaxis address="cd210" size="1" />
    </table2d>
    <table1d name="Advance Multiplier (Initial)" address="cc52c" />
    <table1d name="Advance Multiplier Step Value" address="cc554" />
    <table3d name="Requested Torque A (Accelerator Pedal)" address="de318" userlevel="0">
        <xaxis address="de27c" elements="17" size="1" />
        <yaxis address="de2c0" elements="22" size="1" />
    </table3d>
    <table3d name="Requested Torque B (Accelerator Pedal)" address="de6a0" userlevel="0">
        <xaxis address="de604" elements="17" size="1" />
        <yaxis address="de648" elements="22" size="1" />
    </table3d>
    <table3d name="Requested Torque C (Accelerator Pedal)" address="dea28" userlevel="0">
        <xaxis address="de98c" elements="17" size="1" />
        <yaxis address="de9d0" elements="22" size="1" />
    </table3d>
    <table3d name="Target Throttle Plate Position A (Requested Torque)" address="dbeb4" userlevel="0">
        <xaxis address="dbdf4" elements="26" size="1" />
        <yaxis address="dbe5c" elements="22" size="1" />
    </table3d>
    <table3d name="Target Throttle Plate Position B (Requested Torque)" address="dc3ec" userlevel="0">
        <xaxis address="dc32c" elements="26" size="1" />
        <yaxis address="dc394" elements="22" size="1" />
    </table3d>
    <table3d name="Target Throttle Plate Position C (Requested Torque)" address="dc924" userlevel="0">
        <xaxis address="dc864" elements="26" size="1" />
        <yaxis address="dc8cc" elements="22" size="1" />
    </table3d>
    <table3d name="Target Throttle Plate Position D (Requested Torque)" address="dce5c" userlevel="0">
        <xaxis address="dcd9c" elements="26" size="1" />
        <yaxis address="dce04" elements="22" size="1" />
    </table3d>
    <table3d name="Target Throttle Plate Position E (Requested Torque)" address="dd394" userlevel="0">
        <xaxis address="dd2d4" elements="26" size="1" />
        <yaxis address="dd33c" elements="22" size="1" />
    </table3d>
    <table3d name="Target Throttle Plate Position F (Requested Torque)" address="dd8cc" userlevel="0">
        <xaxis address="dd80c" elements="26" size="1" />
        <yaxis address="dd874" elements="22" size="1" />
    </table3d>
    <table3d name="Target Throttle Plate Position G (Requested Torque)" address="dde04" userlevel="0">
        <xaxis address="ddd44" elements="26" size="1" />
        <yaxis address="dddac" elements="22" size="1" />
    </table3d>
    <table1d name="Rev Limit (Fuel Cut)" address="c7b88" />
    <table1d name="Speed Limiting (Fuel Cut)" address="c7bd0" />
    <table1d name="Speed Limiting A (Throttle)" address="db840" />
    <table1d name="Speed Limiting B (Throttle)" address="db84c" />
    <table2d name="Fuel Temp Sensor Scaling" address="d0948" userlevel="0">
        <yaxis address="d08d0" size="1" />
    </table2d>
    <table2d name="Intake Temp Sensor Scaling" address="9a0a0" userlevel="0">
        <yaxis address="9a028" size="1" />
    </table2d>
    <table2d name="Coolant Temp Sensor Scaling" address="d07e0" userlevel="0">
        <yaxis address="d0770" size="1" />
    </table2d>
    <table1d name="Radiator Fan Modes A (ECT)" address="d11e8" />
    <table1d name="Radiator Fan Modes B (ECT)" address="d11f8" />
    <table1d name="Radiator Fan Modes (Veh. Speed)" address="d1218" />
    <table1d name="Atmospheric Pressure Sensor Scaling_" address="c0248" />
    <table2d name="Idle Speed Target A" address="cefd4" userlevel="0">
        <yaxis address="cea30" size="1" />
    </table2d>
    <table2d name="Idle Speed Target B" address="cf014" userlevel="0">
        <yaxis address="cea30" size="1" />
    </table2d>
    <table2d name="Idle Speed Target C" address="cf054" userlevel="0">
        <yaxis address="cea30" size="1" />
    </table2d>
    <table2d name="Idle Speed Target D" address="cf094" userlevel="0">
        <yaxis address="cea30" size="1" />
    </table2d>
    <table2d name="Idle Speed Target E" address="cf0d4" userlevel="0">
        <yaxis address="cea30" size="1" />
    </table2d>
    <table2d name="Idle Speed Target F" address="cf114" userlevel="0">
        <yaxis address="cea30" size="1" />
    </table2d>
    <table1d name="Force Pass Readiness Monitors" address="84832" />
    <table1d name="(P0000) PASS CODE (NO DTC DETECTED)" address="93391" />
    <table1d name="(P0000) PASS CODE (NO DTC DETECTED)" address="93392" />
    <table1d name="(P0026) OSV SOLENOID VALVE CIRCUIT RANGE/PERF B1" address="933ec" />
    <table1d name="(P0028) OSV SOLENOID VALVE CIRCUIT RANGE/PERF B2" address="933e9" />
    <table1d name="(P0030) FRONT O2 SENSOR RANGE/PERF" address="933bf" />
    <table1d name="(P0031) FRONT O2 SENSOR LOW INPUT" address="933a0" />
    <table1d name="(P0032) FRONT O2 SENSOR HIGH INPUT" address="9339e" />
    <table1d name="(P0037) REAR O2 SENSOR LOW INPUT" address="9339f" />
    <table1d name="(P0038) REAR O2 SENSOR HIGH INPUT" address="9339d" />
    <table1d name="(P0068) MAP SENSOR RANGE/PERF" address="933b9" />
    <table1d name="(P0076) INTAKE VALVE CIRCUIT LOW (BANK 1)" address="933ee" />
    <table1d name="(P0077) INTAKE VALVE CONTROL HIGH (BANK 1)" address="933ed" />
    <table1d name="(P0082) INTAKE VALVE CONTROL LOW (BANK 2)" address="933eb" />
    <table1d name="(P0083) INTAKE VALVE CONTROL HIGH (BANK 2)" address="933ea" />
    <table1d name="(P0101) MAF SENSOR RANGE/PERF" address="933bb" />
    <table1d name="(P0102) MAF SENSOR LOW INPUT" address="9334d" />
    <table1d name="(P0103) MAF SENSOR HIGH INPUT" address="9334e" />
    <table1d name="(P0107) MAP SENSOR LOW INPUT" address="933a1" />
    <table1d name="(P0108) MAP SENSOR HIGH INPUT" address="933a2" />
    <table1d name="(P0111) IAT SENSOR RANGE/PERF" address="9339c" />
    <table1d name="(P0112) IAT SENSOR LOW INPUT" address="9339a" />
    <table1d name="(P0113) IAT SENSOR HIGH INPUT" address="9339b" />
    <table1d name="(P0117) COOLANT TEMP SENSOR LOW INPUT" address="93356" />
    <table1d name="(P0118) COOLANT TEMP SENSOR HIGH INPUT" address="93357" />
    <table1d name="(P0122) TPS A LOW INPUT" address="93354" />
    <table1d name="(P0123) TPS A HIGH INPUT" address="93355" />
    <table1d name="(P0125) INSUFFICIENT COOLANT TEMP (FUELING)" address="93359" />
    <table1d name="(P0126) INSUFFICIENT COOLANT TEMP (OPERATION)" address="933f8" />
    <table1d name="(P0128) THERMOSTAT MALFUNCTION" address="933a7" />
    <table1d name="(P0131) FRONT O2 SENSOR LOW INPUT" address="93394" />